export const DEV_URL = 'http://localhost:5000'
export const IPFS_INFURA_URL = 'https://ipfs.infura.io/ipfs'
// export const FETCH_COUNTRIES = 'https://restcountries.eu/rest/v2/all'
export const FETCH_COUNTRIES = 'https://api.first.org/data/v1/countries'
export const ROPSTEN_ETHERSCAN_URL = 'https://ropsten.etherscan.io/address'
